version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-3-211-48-92.compute-1.amazonaws.com
            database: ddpbp6maqlokh7
            user: dknpogpzeijxpm
            password: 906bc49cebd2c8a1485c21b360dc724395fb6f642f488b40b7b0959f686dfead
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
