version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            database: prisma_db_postgres
            user: root
            password: rootpass
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: true
